use std::arch::asm;

#[inline(never)]
pub fn widening_mul_256(
    mem: &mut [u8],
    dst_start: usize,
    a_start: usize,
    b_start: usize,
    len: usize,
) {
    // Alignment requirements since we will essentially cast *mut [u8]
    // into *mut [u64]
    debug_assert!(mem as *mut [u8] as *mut u8 as usize % 8 == 0);
    debug_assert!(dst_start % 8 == 0);
    debug_assert!(b_start % 8 == 0);
    debug_assert!(a_start % 8 == 0);

    for i in 0..len {
        // Inspired from https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/mul_amd64.h#L1
        unsafe {
            asm!(
                "mov rax, [rsi + 0]",
                "mul qword ptr [rcx + 0]",
                "mov r8, rax",
                "mov r9, rdx",
                "mov rax, [rsi + 0]",
                "mul qword ptr [rcx + 8]",
                "add r9, rax",
                "adc rdx, 0",
                "mov r10, rdx",
                "mov rax, [rsi + 0]",
                "mul qword ptr [rcx + 16]",
                "add r10, rax",
                "adc rdx, 0",
                "mov r11, rdx",
                "mov rax, [rsi + 0]",
                "mul qword ptr [rcx + 24]",
                "add r11, rax",
                "adc rdx, 0",
                "mov r12, rdx",
                "",
                "mov [rdi + 0], r8",
                "mov [rdi + 8], r9",
                "mov [rdi + 16], r10",
                "mov [rdi + 24], r11",
                "mov [rdi + 32], r12",
                "",
                "mov rax, [rsi + 8]",
                "mul qword ptr [rcx + 0]",
                "mov r8, rax",
                "mov r9, rdx",
                "mov rax, [rsi + 8]",
                "mul qword ptr [rcx + 8]",
                "add r9, rax",
                "adc rdx, 0",
                "mov r10, rdx",
                "mov rax, [rsi + 8]",
                "mul qword ptr [rcx + 16]",
                "add r10, rax",
                "adc rdx, 0",
                "mov r11, rdx",
                "mov rax, [rsi + 8]",
                "mul qword ptr [rcx + 24]",
                "add r11, rax",
                "adc rdx, 0",
                "mov r12, rdx",
                "",
                "add r8, [rdi + 8]",
                "adc r9, [rdi + 16]",
                "adc r10, [rdi + 24]",
                "adc r11, [rdi + 32]",
                "adc r12, 0",
                "mov [rdi + 8], r8",
                "mov [rdi + 16], r9",
                "mov [rdi + 24], r10",
                "mov [rdi + 32], r11",
                "mov [rdi + 40], r12",
                "",
                "mov rax, [rsi + 16]",
                "mul qword ptr [rcx + 0]",
                "mov r8, rax",
                "mov r9, rdx",
                "mov rax, [rsi + 16]",
                "mul qword ptr [rcx + 8]",
                "add r9, rax",
                "adc rdx, 0",
                "mov r10, rdx",
                "mov rax, [rsi + 16]",
                "mul qword ptr [rcx + 16]",
                "add r10, rax",
                "adc rdx, 0",
                "mov r11, rdx",
                "mov rax, [rsi + 16]",
                "mul qword ptr [rcx + 24]",
                "add r11, rax",
                "adc rdx, 0",
                "mov r12, rdx",
                "",
                "add r8, [rdi + 16]",
                "adc r9, [rdi + 24]",
                "adc r10, [rdi + 32]",
                "adc r11, [rdi + 40]",
                "adc r12, 0",
                "mov [rdi + 16], r8",
                "mov [rdi + 24], r9",
                "mov [rdi + 32], r10",
                "mov [rdi + 40], r11",
                "mov [rdi + 48], r12",
                "",
                "mov rax, [rsi + 24]",
                "mul qword ptr [rcx + 0]",
                "mov r8, rax",
                "mov r9, rdx",
                "mov rax, [rsi + 24]",
                "mul qword ptr [rcx + 8]",
                "add r9, rax",
                "adc rdx, 0",
                "mov r10, rdx",
                "mov rax, [rsi + 24]",
                "mul qword ptr [rcx + 16]",
                "add r10, rax",
                "adc rdx, 0",
                "mov r11, rdx",
                "mov rax, [rsi + 24]",
                "mul qword ptr [rcx + 24]",
                "add r11, rax",
                "adc rdx, 0",
                "mov r12, rdx",
                "",
                "add r8, [rdi + 24]",
                "adc r9, [rdi + 32]",
                "adc r10, [rdi + 40]",
                "adc r11, [rdi + 48]",
                "adc r12, 0",
                "mov [rdi + 24], r8",
                "mov [rdi + 32], r9",
                "mov [rdi + 40], r10",
                "mov [rdi + 48], r11",
                "mov [rdi + 56], r12",
                in("rsi") mem.as_ptr() as usize + a_start + i * 32,
                in("rcx") mem.as_ptr() as usize + b_start + i * 32,
                in("rdi") mem.as_ptr() as usize + dst_start + i * 64,
                lateout("r12") _,
                clobber_abi("sysv64"),
                clobber_abi("win64"),
            );
        }
    }
}
